[package]
name = "rust-graphql-mysql"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8", features = ["mysql", "runtime-tokio", "rust_decimal", "chrono"] }

async-graphql = { version = "7.0", features = ["decimal", "chrono"] }
rust_decimal = "1.36"
async-trait = "0.1"

askama = "0.15.5"
dotenvy = "0.15"
tower-http = { version = "0.6.7", features = ["cors", "limit", "fs"] } # For setting body limits
argon2 = "0.5"
password-hash = "0.5"    
bcrypt = "0.19.0"
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
chrono = { version = "0.4", features = ["serde"] }
totp-rs = { version = "^5.7.0", features = ["gen_secret", "otpauth", "qr"] }
base32 = "0.5.1"
data-encoding = "2.9.0"

# Web server
axum = { version = "0.8.8", features = ["macros"] }
async-graphql-axum = "7.2.1" 
# Asynchronous runtime
tokio = { version = "1.0", features = ["full"] }
actix-web = "4.13.0"
axum-extra = { version = "0.12", features = ["typed-header"] }
headers = "0.4" 
